#!/usr/bin/env python3
"""
Convert OKLCH color values from prototype.css :root to sRGB hex for Theme.qml.
Run once when hue changes; output is inlined into Theme.qml.

Usage: python3 scripts/gen-theme-colors.py
"""
import math


def oklch_to_hex(L: float, C: float, H_deg: float) -> str:
    H = math.radians(H_deg)
    a = C * math.cos(H)
    b = C * math.sin(H)

    l_ = L + 0.3963377774 * a + 0.2158037573 * b
    m_ = L - 0.1055613458 * a - 0.0638541728 * b
    s_ = L - 0.0894841775 * a - 1.2914855480 * b
    lc = l_ ** 3
    mc = m_ ** 3
    sc = s_ ** 3

    r =  4.0767416621 * lc - 3.3077115913 * mc + 0.2309699292 * sc
    g = -1.2684380046 * lc + 2.6097574011 * mc - 0.3413193965 * sc
    bv = -0.0041960863 * lc - 0.7034186147 * mc + 1.7076147010 * sc

    def gamma(c: float) -> float:
        c = max(0.0, min(1.0, c))
        return 12.92 * c if c <= 0.0031308 else 1.055 * c ** (1 / 2.4) - 0.055

    ri = round(gamma(r) * 255)
    gi = round(gamma(g) * 255)
    bi = round(gamma(bv) * 255)
    return f"#{ri:02x}{gi:02x}{bi:02x}"


HUE = 288  # matches --hue in prototype.css :root

COLORS = {
    "purple":     oklch_to_hex(0.62, 0.17, HUE),
    "purpleSoft": oklch_to_hex(0.78, 0.12, HUE),
    "purpleDeep": oklch_to_hex(0.42, 0.15, HUE),
    "purpleGlow": oklch_to_hex(0.62, 0.18, HUE),  # used at alpha 0.20
    "purpleTint": oklch_to_hex(0.62, 0.18, HUE),  # used at alpha 0.10
    # ink colors: same base #f0ecfa, different alphas (per prototype.css)
    "ink100": "#f0ecfa",
}

if __name__ == "__main__":
    print("// Generated by scripts/gen-theme-colors.py — DO NOT EDIT BY HAND.")
    for name, hex_val in COLORS.items():
        print(f"    readonly property color {name}: \"{hex_val}\"")
    print()
    print("Colors:")
    for name, hex_val in COLORS.items():
        print(f"  {name}: {hex_val}")
